### ISSUE TITLE
i trained my model in tensorflow 2.5.0 but now i need a compatible .h5 model for tensorflow 1.11.0

### ISSUE THREAD

**Issue by ksharm50** [OlofHarrysson/tensorflow-model-converter#3]
i tried your project and like what you are doing can we extent the compatibility to newer version of tensorflow ? please help
otherwise i get this error:
`('Unrecognized keyword arguments:', dict_keys(['ragged'])): ValueError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 50, in lambda_handler
    load_model(local_path_model)
  File "/opt/python/tensorflow/python/keras/engine/saving.py", line 230, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/opt/python/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/opt/python/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/opt/python/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/opt/python/tensorflow/python/keras/engine/sequential.py", line 339, in from_config
    custom_objects=custom_objects)
  File "/opt/python/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/opt/python/tensorflow/python/keras/utils/generic_utils.py", line 175, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/opt/python/tensorflow/python/keras/engine/base_layer.py", line 1617, in from_config
    return cls(**config)
  File "/opt/python/tensorflow/python/keras/engine/input_layer.py", line 70, in __init__
    raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))`

**Comment by OlofHarrysson** [comment]
Hello, yes it would be great to offer support for later tensorflow versions. Do you mind sharing the model-file that you want to convert to 1.11.0? Then I can try to convert it

**Comment by ksharm50** [comment]
yes i can share the file but where ? i trained the model in tensorflow 2.5.0 but for some reason for deploying i can't use above 1.11.0  i have i h5 format and .pb in which format you want ?

**Comment by OlofHarrysson** [comment]
Ok I understand. Upload both the .h5 and .pb files to some file-sharing website and post the link here so that I can download them. Otherwise, what's your email/whatsapp and I'll send you a message there :)

**Comment by kunalsharmagnome** [comment]
I emailed you On the email you shared on github

**Comment by ksharm50** [comment]
I mailed you on your email harrysson.olof@gmail.com

**Comment by OlofHarrysson** [comment]
Hello Kunal,

It seems that the script doesn’t work for this model. I tracked it down to a layer called Rescaling, found early on in the model. https://www.tensorflow.org/versions/r2.5/api_docs/python/tf/keras/layers/experimental/preprocessing/Rescaling

This layer doesn’t exist in earlier versions of tensorflow.

Another problem I found was that there now is a “groups” keyword in the conv-2d layer that wasn’t there in previous versions.

I don’t think that I’ll be able to look further into this problem. The most well known tool to convert between model formats is the onnx-project https://onnx.ai/. Maybe that tool can do it for you

**Comment by ksharm50** [comment]
thanks @OlofHarrysson  for you help it's very insightful i also came to this conclusion from my research but i wanted to confirm . in the end docker came to the rescue haha :)

**Comment by Lad4life** [comment]
Hi, @kunalsharmagnome, I am trying to resolve the same issue you discussed in this post about a loading a new model in an older version of tensorflow. I was wondering if you would be will to contact me about the solution you found? I am relatively new to neural networks and have never used docker or onnx and I would really appreciate any information you could give! Thank you!

**Comment by ksharm50** [comment]
@Lad4life it was not possible because tensorflow changed the way they use to build models in previous versions . so it's better to train it again in older version.
